### ISSUE TITLE
The executable does nothing

### ISSUE THREAD

**Issue by MortalCombatWombat** [AritxOnly/Qt-AbletonLive_ThemeEditor#5] opened 2024-10-08 04:40 UTC

**Comment by AritxOnly** [comment] 2024-10-11 00:03
Could you please tell me which operating system you are using? 
Is it the .exe executable or macOS excecutable?

**Comment by MortalCombatWombat** [comment] 2024-10-11 10:19
It's the .exe. I'm using W10. Thanks

**Comment by AritxOnly** [comment] 2024-10-12 07:10
[Download](https://github.com/AritxOnly/Qt-AbletonLive_ThemeEditor/releases/download/v1.0/AbletonLiveThemeEditor-win-x64.exe)
The file you downloaded is from this link?
Does the .exe not startup or just the application doesn't function well?
Are there any error message involves Qt6 or some .dll files?
If so, any screenshots or details could help me solve the problem, thanks.
ps: Because I'm using a computer that runs win11, so it's hard to say what the problem is by your simple comments. And as I downloaded the file from release page, it actually works.

**Comment by MortalCombatWombat** [comment] 2024-10-14 05:38
Opening the executable, the mouse changes to the Loading icon, but the application won't start at all, even using Admin rights. Checked the Task Manager and there's nothing (neither any error message). Downloaded it via the release, tested again today with the provided link. Thanks for answering.

**Comment by AritxOnly** [comment] 2024-10-14 07:13
I uploaded a zip instead of the boxed exe, please try again the exe in the zip file.
I supposed something went wrong in the vbox exe file

**Comment by AritxOnly** [comment] 2024-10-18 00:58
> Opening the executable, the mouse changes to the Loading icon, but the application won't start at all, even using Admin rights. Checked the Task Manager and there's nothing (neither any error message). Downloaded it via the release, tested again today with the provided link. Thanks for answering.

If the zip version works, I will close this issue. So please let me know, thanks

**Comment by MortalCombatWombat** [comment] 2024-10-19 02:36
I tried running the zip version, but the problem remains. Not a trace of any process related to the Theme Editor. Sorry for the bother. What info about my system could help you?

**Comment by AritxOnly** [comment] 2024-10-24 06:09
Well that was quite sad. I suppose it should be something wrong with the Qt runner environment and maybe because I compile it with MinGW64 on Win11 machine. But because I don't have another windows machine to test it, I can't figure out what happened.
Have you got any experience in compiling with Qt? If so, I suppose you can compile it by yourself. Otherwise, I may try to add a log output function on the next beta and if possible, may trace the problem somehow.

**Comment by MortalCombatWombat** [comment] 2024-10-25 21:38
I don't have expecience compiling, but if you could link any resource that could help I'll attempt to do it. I'm really willing to try the editor out as I make Live themes on a regular basis. Thanks for your patience :)

**Comment by AritxOnly** [comment] 2024-10-25 22:18
Okay, I will give you few instructions.
First of all, download Qt Creator and Qt(select open-source version which is free) from https://www.qt.io/download
Then download the repository using "clone"
open .qrc file up by using qt creator, choose MSVC2019 to compile it. Then all done. Here's what you can try

**Comment by AritxOnly** [comment] 2024-12-12 03:13
> I don't have expecience compiling, but if you could link any resource that could help I'll attempt to do it. I'm really willing to try the editor out as I make Live themes on a regular basis. Thanks for your patience :)

Hello, I supposed I debugged it out using my friend's computer. I will make a few more attempts and give you the link to have a try. Thanks for your support so much!

**Comment by AritxOnly** [comment] 2024-12-12 15:30
Hello, I have fix the bug, try it out!
https://github.com/AritxOnly/Qt-AbletonLive_ThemeEditor/releases/tag/v1.0.1

**Closed as completed by AritxOnly** 2024-12-12 15:30 UTC

**Comment by MortalCombatWombat** [comment] 2024-12-13 01:52
[image: image.png]

Thanks, now it opens correctly :)
